// Code generated by go-swagger; DO NOT EDIT.

package socks5_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// UpdateSocks5ServerReader is a Reader for the UpdateSocks5Server structure.
type UpdateSocks5ServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSocks5ServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateSocks5ServerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateSocks5ServerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateSocks5ServerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewUpdateSocks5ServerConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateSocks5ServerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateSocks5ServerNoContent creates a UpdateSocks5ServerNoContent with default headers values
func NewUpdateSocks5ServerNoContent() *UpdateSocks5ServerNoContent {
	return &UpdateSocks5ServerNoContent{}
}

/*
UpdateSocks5ServerNoContent describes a response with status code 204, with default header values.

ok
*/
type UpdateSocks5ServerNoContent struct {
}

// IsSuccess returns true when this update socks5 server no content response has a 2xx status code
func (o *UpdateSocks5ServerNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update socks5 server no content response has a 3xx status code
func (o *UpdateSocks5ServerNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update socks5 server no content response has a 4xx status code
func (o *UpdateSocks5ServerNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update socks5 server no content response has a 5xx status code
func (o *UpdateSocks5ServerNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update socks5 server no content response a status code equal to that given
func (o *UpdateSocks5ServerNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the update socks5 server no content response
func (o *UpdateSocks5ServerNoContent) Code() int {
	return 204
}

func (o *UpdateSocks5ServerNoContent) Error() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerNoContent ", 204)
}

func (o *UpdateSocks5ServerNoContent) String() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerNoContent ", 204)
}

func (o *UpdateSocks5ServerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSocks5ServerBadRequest creates a UpdateSocks5ServerBadRequest with default headers values
func NewUpdateSocks5ServerBadRequest() *UpdateSocks5ServerBadRequest {
	return &UpdateSocks5ServerBadRequest{}
}

/*
UpdateSocks5ServerBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type UpdateSocks5ServerBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this update socks5 server bad request response has a 2xx status code
func (o *UpdateSocks5ServerBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update socks5 server bad request response has a 3xx status code
func (o *UpdateSocks5ServerBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update socks5 server bad request response has a 4xx status code
func (o *UpdateSocks5ServerBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update socks5 server bad request response has a 5xx status code
func (o *UpdateSocks5ServerBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update socks5 server bad request response a status code equal to that given
func (o *UpdateSocks5ServerBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update socks5 server bad request response
func (o *UpdateSocks5ServerBadRequest) Code() int {
	return 400
}

func (o *UpdateSocks5ServerBadRequest) Error() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateSocks5ServerBadRequest) String() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateSocks5ServerBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *UpdateSocks5ServerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSocks5ServerNotFound creates a UpdateSocks5ServerNotFound with default headers values
func NewUpdateSocks5ServerNotFound() *UpdateSocks5ServerNotFound {
	return &UpdateSocks5ServerNotFound{}
}

/*
UpdateSocks5ServerNotFound describes a response with status code 404, with default header values.

resource not found
*/
type UpdateSocks5ServerNotFound struct {
	Payload *vproxy_client_model.Error404
}

// IsSuccess returns true when this update socks5 server not found response has a 2xx status code
func (o *UpdateSocks5ServerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update socks5 server not found response has a 3xx status code
func (o *UpdateSocks5ServerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update socks5 server not found response has a 4xx status code
func (o *UpdateSocks5ServerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update socks5 server not found response has a 5xx status code
func (o *UpdateSocks5ServerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update socks5 server not found response a status code equal to that given
func (o *UpdateSocks5ServerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update socks5 server not found response
func (o *UpdateSocks5ServerNotFound) Code() int {
	return 404
}

func (o *UpdateSocks5ServerNotFound) Error() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerNotFound  %+v", 404, o.Payload)
}

func (o *UpdateSocks5ServerNotFound) String() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerNotFound  %+v", 404, o.Payload)
}

func (o *UpdateSocks5ServerNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *UpdateSocks5ServerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSocks5ServerConflict creates a UpdateSocks5ServerConflict with default headers values
func NewUpdateSocks5ServerConflict() *UpdateSocks5ServerConflict {
	return &UpdateSocks5ServerConflict{}
}

/*
UpdateSocks5ServerConflict describes a response with status code 409, with default header values.

conflict
*/
type UpdateSocks5ServerConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this update socks5 server conflict response has a 2xx status code
func (o *UpdateSocks5ServerConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update socks5 server conflict response has a 3xx status code
func (o *UpdateSocks5ServerConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update socks5 server conflict response has a 4xx status code
func (o *UpdateSocks5ServerConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this update socks5 server conflict response has a 5xx status code
func (o *UpdateSocks5ServerConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this update socks5 server conflict response a status code equal to that given
func (o *UpdateSocks5ServerConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the update socks5 server conflict response
func (o *UpdateSocks5ServerConflict) Code() int {
	return 409
}

func (o *UpdateSocks5ServerConflict) Error() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerConflict  %+v", 409, o.Payload)
}

func (o *UpdateSocks5ServerConflict) String() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerConflict  %+v", 409, o.Payload)
}

func (o *UpdateSocks5ServerConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *UpdateSocks5ServerConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSocks5ServerInternalServerError creates a UpdateSocks5ServerInternalServerError with default headers values
func NewUpdateSocks5ServerInternalServerError() *UpdateSocks5ServerInternalServerError {
	return &UpdateSocks5ServerInternalServerError{}
}

/*
UpdateSocks5ServerInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type UpdateSocks5ServerInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this update socks5 server internal server error response has a 2xx status code
func (o *UpdateSocks5ServerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update socks5 server internal server error response has a 3xx status code
func (o *UpdateSocks5ServerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update socks5 server internal server error response has a 4xx status code
func (o *UpdateSocks5ServerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update socks5 server internal server error response has a 5xx status code
func (o *UpdateSocks5ServerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update socks5 server internal server error response a status code equal to that given
func (o *UpdateSocks5ServerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update socks5 server internal server error response
func (o *UpdateSocks5ServerInternalServerError) Code() int {
	return 500
}

func (o *UpdateSocks5ServerInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateSocks5ServerInternalServerError) String() string {
	return fmt.Sprintf("[PUT /socks5-server/{socks5}][%d] updateSocks5ServerInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateSocks5ServerInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *UpdateSocks5ServerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
