---
apiVersion: v1
kind: Namespace
metadata:
  name: vproxy-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vproxy-service-account
  namespace: vproxy-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vproxy-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - secrets
  verbs: [get, list, watch]
- apiGroups:
  - "vproxy.cc"
  resources:
  - "*"
  verbs: [get, list, watch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vproxy-cluster-role-binding
  namespace: vproxy-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vproxy-cluster-role
subjects:
- kind: ServiceAccount
  name: vproxy-service-account
  namespace: vproxy-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproxy-gateway
  namespace: vproxy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproxy-gateway
  template:
    metadata:
      labels:
        app: vproxy-gateway
    spec:
      serviceAccountName: vproxy-service-account
      volumes:
      - name: vpctl
        emptyDir: {}
      containers:
      - name: controller
        image: wkgcass/vpctl:latest
        imagePullPolicy: IfNotPresent
        args:
        - '--labels={"app":"vproxy-gateway"}'
        volumeMounts:
        - name: vpctl
          mountPath: /root/vpctl
      - name: vproxy
        args:
        - noLoadLast
        - noSave
        - sigIntDirectlyShutdown
        - noStdIOController
        volumeMounts:
        - name: vpctl
          mountPath: /root/vpctl
        image: wkgcass/vproxy:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - --connect-timeout
            - "1"
            - 127.0.0.1:18776/healthz
          initialDelaySeconds: 5
          periodSeconds: 5
