// Code generated by go-swagger; DO NOT EDIT.

package event_loop_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RemoveEventLoopGroupReader is a Reader for the RemoveEventLoopGroup structure.
type RemoveEventLoopGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveEventLoopGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveEventLoopGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveEventLoopGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRemoveEventLoopGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveEventLoopGroupNoContent creates a RemoveEventLoopGroupNoContent with default headers values
func NewRemoveEventLoopGroupNoContent() *RemoveEventLoopGroupNoContent {
	return &RemoveEventLoopGroupNoContent{}
}

/*RemoveEventLoopGroupNoContent handles this case with default header values.

ok
*/
type RemoveEventLoopGroupNoContent struct {
}

func (o *RemoveEventLoopGroupNoContent) Error() string {
	return fmt.Sprintf("[DELETE /event-loop-group/{elg}][%d] removeEventLoopGroupNoContent ", 204)
}

func (o *RemoveEventLoopGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveEventLoopGroupBadRequest creates a RemoveEventLoopGroupBadRequest with default headers values
func NewRemoveEventLoopGroupBadRequest() *RemoveEventLoopGroupBadRequest {
	return &RemoveEventLoopGroupBadRequest{}
}

/*RemoveEventLoopGroupBadRequest handles this case with default header values.

Invalid input
*/
type RemoveEventLoopGroupBadRequest struct {
}

func (o *RemoveEventLoopGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /event-loop-group/{elg}][%d] removeEventLoopGroupBadRequest ", 400)
}

func (o *RemoveEventLoopGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveEventLoopGroupNotFound creates a RemoveEventLoopGroupNotFound with default headers values
func NewRemoveEventLoopGroupNotFound() *RemoveEventLoopGroupNotFound {
	return &RemoveEventLoopGroupNotFound{}
}

/*RemoveEventLoopGroupNotFound handles this case with default header values.

EventLoopGroup not found
*/
type RemoveEventLoopGroupNotFound struct {
}

func (o *RemoveEventLoopGroupNotFound) Error() string {
	return fmt.Sprintf("[DELETE /event-loop-group/{elg}][%d] removeEventLoopGroupNotFound ", 404)
}

func (o *RemoveEventLoopGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
