// Code generated by go-swagger; DO NOT EDIT.

package vproxy_client_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerGroupCreate server group create
// swagger:model ServerGroupCreate
type ServerGroupCreate struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// consider the server unhealthy after $down times of failed health checks
	// Required: true
	Down *int64 `json:"down"`

	// the event loop group to run health check on
	EventLoopGroup string `json:"eventLoopGroup,omitempty"`

	// method
	Method ServerGroupMethod `json:"method,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// health check period (ms) (interval between two hc)
	// Required: true
	Period *int64 `json:"period"`

	// protocol
	Protocol CheckProtocol `json:"protocol,omitempty"`

	// health check timeout (ms) (timeout before getting expected response)
	// Required: true
	Timeout *int64 `json:"timeout"`

	// consider the server healthy after $up times of successful health checks
	// Required: true
	Up *int64 `json:"up"`
}

// Validate validates this server group create
func (m *ServerGroupCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDown(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerGroupCreate) validateDown(formats strfmt.Registry) error {

	if err := validate.Required("down", "body", m.Down); err != nil {
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validateMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.Method) { // not required
		return nil
	}

	if err := m.Method.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("method")
		}
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validatePeriod(formats strfmt.Registry) error {

	if err := validate.Required("period", "body", m.Period); err != nil {
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validateProtocol(formats strfmt.Registry) error {

	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	if err := m.Protocol.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("protocol")
		}
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validateTimeout(formats strfmt.Registry) error {

	if err := validate.Required("timeout", "body", m.Timeout); err != nil {
		return err
	}

	return nil
}

func (m *ServerGroupCreate) validateUp(formats strfmt.Registry) error {

	if err := validate.Required("up", "body", m.Up); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServerGroupCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerGroupCreate) UnmarshalBinary(b []byte) error {
	var res ServerGroupCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
