// Code generated by go-swagger; DO NOT EDIT.

package vproxy_client_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SmartNodeDelegateDetail smart node delegate detail
// swagger:model SmartNodeDelegateDetail
type SmartNodeDelegateDetail struct {

	// port of the application
	ExposedPort int64 `json:"exposedPort,omitempty"`

	// ip type
	IPType IPType `json:"ipType,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// name of the nic which the application binds on
	Nic string `json:"nic,omitempty"`

	// name of the service to register application node into
	Service string `json:"service,omitempty"`

	// status
	// Enum: [UP DOWN]
	Status string `json:"status,omitempty"`

	// weight of the application node in the service
	Weight int64 `json:"weight,omitempty"`

	// name of the working zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this smart node delegate detail
func (m *SmartNodeDelegateDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIPType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmartNodeDelegateDetail) validateIPType(formats strfmt.Registry) error {

	if swag.IsZero(m.IPType) { // not required
		return nil
	}

	if err := m.IPType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ipType")
		}
		return err
	}

	return nil
}

var smartNodeDelegateDetailTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["UP","DOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		smartNodeDelegateDetailTypeStatusPropEnum = append(smartNodeDelegateDetailTypeStatusPropEnum, v)
	}
}

const (

	// SmartNodeDelegateDetailStatusUP captures enum value "UP"
	SmartNodeDelegateDetailStatusUP string = "UP"

	// SmartNodeDelegateDetailStatusDOWN captures enum value "DOWN"
	SmartNodeDelegateDetailStatusDOWN string = "DOWN"
)

// prop value enum
func (m *SmartNodeDelegateDetail) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, smartNodeDelegateDetailTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SmartNodeDelegateDetail) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SmartNodeDelegateDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmartNodeDelegateDetail) UnmarshalBinary(b []byte) error {
	var res SmartNodeDelegateDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
