// Code generated by go-swagger; DO NOT EDIT.

package vproxy_client_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SmartGroupDelegateDetail smart group delegate detail
// swagger:model SmartGroupDelegateDetail
type SmartGroupDelegateDetail struct {

	// handled group
	HandledGroup *ServerGroupDetail `json:"handledGroup,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// name of the watched service
	Service string `json:"service,omitempty"`

	// name of the watched zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this smart group delegate detail
func (m *SmartGroupDelegateDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHandledGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmartGroupDelegateDetail) validateHandledGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.HandledGroup) { // not required
		return nil
	}

	if m.HandledGroup != nil {
		if err := m.HandledGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("handledGroup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SmartGroupDelegateDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmartGroupDelegateDetail) UnmarshalBinary(b []byte) error {
	var res SmartGroupDelegateDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
