// Code generated by go-swagger; DO NOT EDIT.

package vproxy_client_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Socks5ServerCreate socks5 server create
// swagger:model Socks5ServerCreate
type Socks5ServerCreate struct {

	// event loop group for accepting connections
	AcceptorLoopGroup string `json:"acceptorLoopGroup,omitempty"`

	// binding l4addr
	// Required: true
	Address *string `json:"address"`

	// allow or disallow to proxy to non-backend endpoints
	AllowNonBackend *bool `json:"allowNonBackend,omitempty"`

	// upstream reference for backend servers
	// Required: true
	Backend *string `json:"backend"`

	// input buffer size
	InBufferSize int64 `json:"inBufferSize,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// output buffer size
	OutBufferSize int64 `json:"outBufferSize,omitempty"`

	// security group reference for access control
	SecurityGroup string `json:"securityGroup,omitempty"`

	// event loop group for handling netflow
	WorkerLoopGroup string `json:"workerLoopGroup,omitempty"`
}

// Validate validates this socks5 server create
func (m *Socks5ServerCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBackend(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Socks5ServerCreate) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *Socks5ServerCreate) validateBackend(formats strfmt.Registry) error {

	if err := validate.Required("backend", "body", m.Backend); err != nil {
		return err
	}

	return nil
}

func (m *Socks5ServerCreate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Socks5ServerCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Socks5ServerCreate) UnmarshalBinary(b []byte) error {
	var res Socks5ServerCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
