// Code generated by go-swagger; DO NOT EDIT.

package tcp_lb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// ListTCPLbReader is a Reader for the ListTCPLb structure.
type ListTCPLbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTCPLbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTCPLbOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListTCPLbOK creates a ListTCPLbOK with default headers values
func NewListTCPLbOK() *ListTCPLbOK {
	return &ListTCPLbOK{}
}

/*ListTCPLbOK handles this case with default header values.

ok
*/
type ListTCPLbOK struct {
	Payload []*vproxy_client_model.TCPLb
}

func (o *ListTCPLbOK) Error() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbOK  %+v", 200, o.Payload)
}

func (o *ListTCPLbOK) GetPayload() []*vproxy_client_model.TCPLb {
	return o.Payload
}

func (o *ListTCPLbOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
