// Code generated by go-swagger; DO NOT EDIT.

package tcp_lb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// RemoveTCPLbReader is a Reader for the RemoveTCPLb structure.
type RemoveTCPLbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveTCPLbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveTCPLbNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveTCPLbBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRemoveTCPLbNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewRemoveTCPLbConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveTCPLbInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveTCPLbNoContent creates a RemoveTCPLbNoContent with default headers values
func NewRemoveTCPLbNoContent() *RemoveTCPLbNoContent {
	return &RemoveTCPLbNoContent{}
}

/*RemoveTCPLbNoContent handles this case with default header values.

ok
*/
type RemoveTCPLbNoContent struct {
}

func (o *RemoveTCPLbNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tcp-lb/{tl}][%d] removeTcpLbNoContent ", 204)
}

func (o *RemoveTCPLbNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveTCPLbBadRequest creates a RemoveTCPLbBadRequest with default headers values
func NewRemoveTCPLbBadRequest() *RemoveTCPLbBadRequest {
	return &RemoveTCPLbBadRequest{}
}

/*RemoveTCPLbBadRequest handles this case with default header values.

invalid input parameters
*/
type RemoveTCPLbBadRequest struct {
	Payload *vproxy_client_model.Error400
}

func (o *RemoveTCPLbBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /tcp-lb/{tl}][%d] removeTcpLbBadRequest  %+v", 400, o.Payload)
}

func (o *RemoveTCPLbBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *RemoveTCPLbBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTCPLbNotFound creates a RemoveTCPLbNotFound with default headers values
func NewRemoveTCPLbNotFound() *RemoveTCPLbNotFound {
	return &RemoveTCPLbNotFound{}
}

/*RemoveTCPLbNotFound handles this case with default header values.

resource not found
*/
type RemoveTCPLbNotFound struct {
	Payload *vproxy_client_model.Error404
}

func (o *RemoveTCPLbNotFound) Error() string {
	return fmt.Sprintf("[DELETE /tcp-lb/{tl}][%d] removeTcpLbNotFound  %+v", 404, o.Payload)
}

func (o *RemoveTCPLbNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *RemoveTCPLbNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTCPLbConflict creates a RemoveTCPLbConflict with default headers values
func NewRemoveTCPLbConflict() *RemoveTCPLbConflict {
	return &RemoveTCPLbConflict{}
}

/*RemoveTCPLbConflict handles this case with default header values.

conflict
*/
type RemoveTCPLbConflict struct {
	Payload *vproxy_client_model.Error409
}

func (o *RemoveTCPLbConflict) Error() string {
	return fmt.Sprintf("[DELETE /tcp-lb/{tl}][%d] removeTcpLbConflict  %+v", 409, o.Payload)
}

func (o *RemoveTCPLbConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *RemoveTCPLbConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTCPLbInternalServerError creates a RemoveTCPLbInternalServerError with default headers values
func NewRemoveTCPLbInternalServerError() *RemoveTCPLbInternalServerError {
	return &RemoveTCPLbInternalServerError{}
}

/*RemoveTCPLbInternalServerError handles this case with default header values.

internal error
*/
type RemoveTCPLbInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

func (o *RemoveTCPLbInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /tcp-lb/{tl}][%d] removeTcpLbInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveTCPLbInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *RemoveTCPLbInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
