// Code generated by go-swagger; DO NOT EDIT.

package tcp_lb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateTCPLbReader is a Reader for the UpdateTCPLb structure.
type UpdateTCPLbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTCPLbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateTCPLbNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateTCPLbBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateTCPLbNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateTCPLbNoContent creates a UpdateTCPLbNoContent with default headers values
func NewUpdateTCPLbNoContent() *UpdateTCPLbNoContent {
	return &UpdateTCPLbNoContent{}
}

/*UpdateTCPLbNoContent handles this case with default header values.

ok
*/
type UpdateTCPLbNoContent struct {
}

func (o *UpdateTCPLbNoContent) Error() string {
	return fmt.Sprintf("[PUT /tcp-lb/{tl}][%d] updateTcpLbNoContent ", 204)
}

func (o *UpdateTCPLbNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTCPLbBadRequest creates a UpdateTCPLbBadRequest with default headers values
func NewUpdateTCPLbBadRequest() *UpdateTCPLbBadRequest {
	return &UpdateTCPLbBadRequest{}
}

/*UpdateTCPLbBadRequest handles this case with default header values.

Invalid input
*/
type UpdateTCPLbBadRequest struct {
}

func (o *UpdateTCPLbBadRequest) Error() string {
	return fmt.Sprintf("[PUT /tcp-lb/{tl}][%d] updateTcpLbBadRequest ", 400)
}

func (o *UpdateTCPLbBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTCPLbNotFound creates a UpdateTCPLbNotFound with default headers values
func NewUpdateTCPLbNotFound() *UpdateTCPLbNotFound {
	return &UpdateTCPLbNotFound{}
}

/*UpdateTCPLbNotFound handles this case with default header values.

TcpLb not found
*/
type UpdateTCPLbNotFound struct {
}

func (o *UpdateTCPLbNotFound) Error() string {
	return fmt.Sprintf("[PUT /tcp-lb/{tl}][%d] updateTcpLbNotFound ", 404)
}

func (o *UpdateTCPLbNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
