// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// AddServerGroupInUpstreamReader is a Reader for the AddServerGroupInUpstream structure.
type AddServerGroupInUpstreamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddServerGroupInUpstreamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAddServerGroupInUpstreamNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddServerGroupInUpstreamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAddServerGroupInUpstreamNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAddServerGroupInUpstreamConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddServerGroupInUpstreamInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddServerGroupInUpstreamNoContent creates a AddServerGroupInUpstreamNoContent with default headers values
func NewAddServerGroupInUpstreamNoContent() *AddServerGroupInUpstreamNoContent {
	return &AddServerGroupInUpstreamNoContent{}
}

/*
AddServerGroupInUpstreamNoContent describes a response with status code 204, with default header values.

ok
*/
type AddServerGroupInUpstreamNoContent struct {
}

// IsSuccess returns true when this add server group in upstream no content response has a 2xx status code
func (o *AddServerGroupInUpstreamNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add server group in upstream no content response has a 3xx status code
func (o *AddServerGroupInUpstreamNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add server group in upstream no content response has a 4xx status code
func (o *AddServerGroupInUpstreamNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this add server group in upstream no content response has a 5xx status code
func (o *AddServerGroupInUpstreamNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this add server group in upstream no content response a status code equal to that given
func (o *AddServerGroupInUpstreamNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the add server group in upstream no content response
func (o *AddServerGroupInUpstreamNoContent) Code() int {
	return 204
}

func (o *AddServerGroupInUpstreamNoContent) Error() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamNoContent ", 204)
}

func (o *AddServerGroupInUpstreamNoContent) String() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamNoContent ", 204)
}

func (o *AddServerGroupInUpstreamNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServerGroupInUpstreamBadRequest creates a AddServerGroupInUpstreamBadRequest with default headers values
func NewAddServerGroupInUpstreamBadRequest() *AddServerGroupInUpstreamBadRequest {
	return &AddServerGroupInUpstreamBadRequest{}
}

/*
AddServerGroupInUpstreamBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type AddServerGroupInUpstreamBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this add server group in upstream bad request response has a 2xx status code
func (o *AddServerGroupInUpstreamBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add server group in upstream bad request response has a 3xx status code
func (o *AddServerGroupInUpstreamBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add server group in upstream bad request response has a 4xx status code
func (o *AddServerGroupInUpstreamBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this add server group in upstream bad request response has a 5xx status code
func (o *AddServerGroupInUpstreamBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this add server group in upstream bad request response a status code equal to that given
func (o *AddServerGroupInUpstreamBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the add server group in upstream bad request response
func (o *AddServerGroupInUpstreamBadRequest) Code() int {
	return 400
}

func (o *AddServerGroupInUpstreamBadRequest) Error() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamBadRequest  %+v", 400, o.Payload)
}

func (o *AddServerGroupInUpstreamBadRequest) String() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamBadRequest  %+v", 400, o.Payload)
}

func (o *AddServerGroupInUpstreamBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *AddServerGroupInUpstreamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddServerGroupInUpstreamNotFound creates a AddServerGroupInUpstreamNotFound with default headers values
func NewAddServerGroupInUpstreamNotFound() *AddServerGroupInUpstreamNotFound {
	return &AddServerGroupInUpstreamNotFound{}
}

/*
AddServerGroupInUpstreamNotFound describes a response with status code 404, with default header values.

resource not found
*/
type AddServerGroupInUpstreamNotFound struct {
	Payload *vproxy_client_model.Error404
}

// IsSuccess returns true when this add server group in upstream not found response has a 2xx status code
func (o *AddServerGroupInUpstreamNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add server group in upstream not found response has a 3xx status code
func (o *AddServerGroupInUpstreamNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add server group in upstream not found response has a 4xx status code
func (o *AddServerGroupInUpstreamNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this add server group in upstream not found response has a 5xx status code
func (o *AddServerGroupInUpstreamNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this add server group in upstream not found response a status code equal to that given
func (o *AddServerGroupInUpstreamNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the add server group in upstream not found response
func (o *AddServerGroupInUpstreamNotFound) Code() int {
	return 404
}

func (o *AddServerGroupInUpstreamNotFound) Error() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamNotFound  %+v", 404, o.Payload)
}

func (o *AddServerGroupInUpstreamNotFound) String() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamNotFound  %+v", 404, o.Payload)
}

func (o *AddServerGroupInUpstreamNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *AddServerGroupInUpstreamNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddServerGroupInUpstreamConflict creates a AddServerGroupInUpstreamConflict with default headers values
func NewAddServerGroupInUpstreamConflict() *AddServerGroupInUpstreamConflict {
	return &AddServerGroupInUpstreamConflict{}
}

/*
AddServerGroupInUpstreamConflict describes a response with status code 409, with default header values.

conflict
*/
type AddServerGroupInUpstreamConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this add server group in upstream conflict response has a 2xx status code
func (o *AddServerGroupInUpstreamConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add server group in upstream conflict response has a 3xx status code
func (o *AddServerGroupInUpstreamConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add server group in upstream conflict response has a 4xx status code
func (o *AddServerGroupInUpstreamConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this add server group in upstream conflict response has a 5xx status code
func (o *AddServerGroupInUpstreamConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this add server group in upstream conflict response a status code equal to that given
func (o *AddServerGroupInUpstreamConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the add server group in upstream conflict response
func (o *AddServerGroupInUpstreamConflict) Code() int {
	return 409
}

func (o *AddServerGroupInUpstreamConflict) Error() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamConflict  %+v", 409, o.Payload)
}

func (o *AddServerGroupInUpstreamConflict) String() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamConflict  %+v", 409, o.Payload)
}

func (o *AddServerGroupInUpstreamConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *AddServerGroupInUpstreamConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddServerGroupInUpstreamInternalServerError creates a AddServerGroupInUpstreamInternalServerError with default headers values
func NewAddServerGroupInUpstreamInternalServerError() *AddServerGroupInUpstreamInternalServerError {
	return &AddServerGroupInUpstreamInternalServerError{}
}

/*
AddServerGroupInUpstreamInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type AddServerGroupInUpstreamInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this add server group in upstream internal server error response has a 2xx status code
func (o *AddServerGroupInUpstreamInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add server group in upstream internal server error response has a 3xx status code
func (o *AddServerGroupInUpstreamInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add server group in upstream internal server error response has a 4xx status code
func (o *AddServerGroupInUpstreamInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this add server group in upstream internal server error response has a 5xx status code
func (o *AddServerGroupInUpstreamInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this add server group in upstream internal server error response a status code equal to that given
func (o *AddServerGroupInUpstreamInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the add server group in upstream internal server error response
func (o *AddServerGroupInUpstreamInternalServerError) Code() int {
	return 500
}

func (o *AddServerGroupInUpstreamInternalServerError) Error() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamInternalServerError  %+v", 500, o.Payload)
}

func (o *AddServerGroupInUpstreamInternalServerError) String() string {
	return fmt.Sprintf("[POST /upstream/{ups}/server-group][%d] addServerGroupInUpstreamInternalServerError  %+v", 500, o.Payload)
}

func (o *AddServerGroupInUpstreamInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *AddServerGroupInUpstreamInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
