// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeServerGroupParams creates a new DescribeServerGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeServerGroupParams() *DescribeServerGroupParams {
	return &DescribeServerGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeServerGroupParamsWithTimeout creates a new DescribeServerGroupParams object
// with the ability to set a timeout on a request.
func NewDescribeServerGroupParamsWithTimeout(timeout time.Duration) *DescribeServerGroupParams {
	return &DescribeServerGroupParams{
		timeout: timeout,
	}
}

// NewDescribeServerGroupParamsWithContext creates a new DescribeServerGroupParams object
// with the ability to set a context for a request.
func NewDescribeServerGroupParamsWithContext(ctx context.Context) *DescribeServerGroupParams {
	return &DescribeServerGroupParams{
		Context: ctx,
	}
}

// NewDescribeServerGroupParamsWithHTTPClient creates a new DescribeServerGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeServerGroupParamsWithHTTPClient(client *http.Client) *DescribeServerGroupParams {
	return &DescribeServerGroupParams{
		HTTPClient: client,
	}
}

/*
DescribeServerGroupParams contains all the parameters to send to the API endpoint

	for the describe server group operation.

	Typically these are written to a http.Request.
*/
type DescribeServerGroupParams struct {

	/* Sg.

	   name of the server-group
	*/
	Sg string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the describe server group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeServerGroupParams) WithDefaults() *DescribeServerGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe server group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeServerGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe server group params
func (o *DescribeServerGroupParams) WithTimeout(timeout time.Duration) *DescribeServerGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe server group params
func (o *DescribeServerGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe server group params
func (o *DescribeServerGroupParams) WithContext(ctx context.Context) *DescribeServerGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe server group params
func (o *DescribeServerGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe server group params
func (o *DescribeServerGroupParams) WithHTTPClient(client *http.Client) *DescribeServerGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe server group params
func (o *DescribeServerGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSg adds the sg to the describe server group params
func (o *DescribeServerGroupParams) WithSg(sg string) *DescribeServerGroupParams {
	o.SetSg(sg)
	return o
}

// SetSg adds the sg to the describe server group params
func (o *DescribeServerGroupParams) SetSg(sg string) {
	o.Sg = sg
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeServerGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param sg
	if err := r.SetPathParam("sg", o.Sg); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
