// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// RemoveServerReader is a Reader for the RemoveServer structure.
type RemoveServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveServerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveServerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRemoveServerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewRemoveServerConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveServerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveServerNoContent creates a RemoveServerNoContent with default headers values
func NewRemoveServerNoContent() *RemoveServerNoContent {
	return &RemoveServerNoContent{}
}

/*RemoveServerNoContent handles this case with default header values.

ok
*/
type RemoveServerNoContent struct {
}

func (o *RemoveServerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /server-group/{sg}/server/{svr}][%d] removeServerNoContent ", 204)
}

func (o *RemoveServerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveServerBadRequest creates a RemoveServerBadRequest with default headers values
func NewRemoveServerBadRequest() *RemoveServerBadRequest {
	return &RemoveServerBadRequest{}
}

/*RemoveServerBadRequest handles this case with default header values.

invalid input parameters
*/
type RemoveServerBadRequest struct {
	Payload *vproxy_client_model.Error400
}

func (o *RemoveServerBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /server-group/{sg}/server/{svr}][%d] removeServerBadRequest  %+v", 400, o.Payload)
}

func (o *RemoveServerBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *RemoveServerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveServerNotFound creates a RemoveServerNotFound with default headers values
func NewRemoveServerNotFound() *RemoveServerNotFound {
	return &RemoveServerNotFound{}
}

/*RemoveServerNotFound handles this case with default header values.

resource not found
*/
type RemoveServerNotFound struct {
	Payload *vproxy_client_model.Error404
}

func (o *RemoveServerNotFound) Error() string {
	return fmt.Sprintf("[DELETE /server-group/{sg}/server/{svr}][%d] removeServerNotFound  %+v", 404, o.Payload)
}

func (o *RemoveServerNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *RemoveServerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveServerConflict creates a RemoveServerConflict with default headers values
func NewRemoveServerConflict() *RemoveServerConflict {
	return &RemoveServerConflict{}
}

/*RemoveServerConflict handles this case with default header values.

conflict
*/
type RemoveServerConflict struct {
	Payload *vproxy_client_model.Error409
}

func (o *RemoveServerConflict) Error() string {
	return fmt.Sprintf("[DELETE /server-group/{sg}/server/{svr}][%d] removeServerConflict  %+v", 409, o.Payload)
}

func (o *RemoveServerConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *RemoveServerConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveServerInternalServerError creates a RemoveServerInternalServerError with default headers values
func NewRemoveServerInternalServerError() *RemoveServerInternalServerError {
	return &RemoveServerInternalServerError{}
}

/*RemoveServerInternalServerError handles this case with default header values.

internal error
*/
type RemoveServerInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

func (o *RemoveServerInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /server-group/{sg}/server/{svr}][%d] removeServerInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveServerInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *RemoveServerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
