// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// GetSecurityGroupReader is a Reader for the GetSecurityGroup structure.
type GetSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSecurityGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetSecurityGroupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSecurityGroupOK creates a GetSecurityGroupOK with default headers values
func NewGetSecurityGroupOK() *GetSecurityGroupOK {
	return &GetSecurityGroupOK{}
}

/*
GetSecurityGroupOK describes a response with status code 200, with default header values.

ok
*/
type GetSecurityGroupOK struct {
	Payload *vproxy_client_model.SecurityGroup
}

// IsSuccess returns true when this get security group o k response has a 2xx status code
func (o *GetSecurityGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get security group o k response has a 3xx status code
func (o *GetSecurityGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security group o k response has a 4xx status code
func (o *GetSecurityGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get security group o k response has a 5xx status code
func (o *GetSecurityGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get security group o k response a status code equal to that given
func (o *GetSecurityGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get security group o k response
func (o *GetSecurityGroupOK) Code() int {
	return 200
}

func (o *GetSecurityGroupOK) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *GetSecurityGroupOK) String() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *GetSecurityGroupOK) GetPayload() *vproxy_client_model.SecurityGroup {
	return o.Payload
}

func (o *GetSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.SecurityGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupBadRequest creates a GetSecurityGroupBadRequest with default headers values
func NewGetSecurityGroupBadRequest() *GetSecurityGroupBadRequest {
	return &GetSecurityGroupBadRequest{}
}

/*
GetSecurityGroupBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type GetSecurityGroupBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this get security group bad request response has a 2xx status code
func (o *GetSecurityGroupBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get security group bad request response has a 3xx status code
func (o *GetSecurityGroupBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security group bad request response has a 4xx status code
func (o *GetSecurityGroupBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get security group bad request response has a 5xx status code
func (o *GetSecurityGroupBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get security group bad request response a status code equal to that given
func (o *GetSecurityGroupBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get security group bad request response
func (o *GetSecurityGroupBadRequest) Code() int {
	return 400
}

func (o *GetSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupBadRequest  %+v", 400, o.Payload)
}

func (o *GetSecurityGroupBadRequest) String() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupBadRequest  %+v", 400, o.Payload)
}

func (o *GetSecurityGroupBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *GetSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupNotFound creates a GetSecurityGroupNotFound with default headers values
func NewGetSecurityGroupNotFound() *GetSecurityGroupNotFound {
	return &GetSecurityGroupNotFound{}
}

/*
GetSecurityGroupNotFound describes a response with status code 404, with default header values.

resource not found
*/
type GetSecurityGroupNotFound struct {
	Payload *vproxy_client_model.Error404
}

// IsSuccess returns true when this get security group not found response has a 2xx status code
func (o *GetSecurityGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get security group not found response has a 3xx status code
func (o *GetSecurityGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security group not found response has a 4xx status code
func (o *GetSecurityGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get security group not found response has a 5xx status code
func (o *GetSecurityGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get security group not found response a status code equal to that given
func (o *GetSecurityGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get security group not found response
func (o *GetSecurityGroupNotFound) Code() int {
	return 404
}

func (o *GetSecurityGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetSecurityGroupNotFound) String() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetSecurityGroupNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *GetSecurityGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupConflict creates a GetSecurityGroupConflict with default headers values
func NewGetSecurityGroupConflict() *GetSecurityGroupConflict {
	return &GetSecurityGroupConflict{}
}

/*
GetSecurityGroupConflict describes a response with status code 409, with default header values.

conflict
*/
type GetSecurityGroupConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this get security group conflict response has a 2xx status code
func (o *GetSecurityGroupConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get security group conflict response has a 3xx status code
func (o *GetSecurityGroupConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security group conflict response has a 4xx status code
func (o *GetSecurityGroupConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get security group conflict response has a 5xx status code
func (o *GetSecurityGroupConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get security group conflict response a status code equal to that given
func (o *GetSecurityGroupConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get security group conflict response
func (o *GetSecurityGroupConflict) Code() int {
	return 409
}

func (o *GetSecurityGroupConflict) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupConflict  %+v", 409, o.Payload)
}

func (o *GetSecurityGroupConflict) String() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupConflict  %+v", 409, o.Payload)
}

func (o *GetSecurityGroupConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *GetSecurityGroupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupInternalServerError creates a GetSecurityGroupInternalServerError with default headers values
func NewGetSecurityGroupInternalServerError() *GetSecurityGroupInternalServerError {
	return &GetSecurityGroupInternalServerError{}
}

/*
GetSecurityGroupInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type GetSecurityGroupInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this get security group internal server error response has a 2xx status code
func (o *GetSecurityGroupInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get security group internal server error response has a 3xx status code
func (o *GetSecurityGroupInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security group internal server error response has a 4xx status code
func (o *GetSecurityGroupInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get security group internal server error response has a 5xx status code
func (o *GetSecurityGroupInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get security group internal server error response a status code equal to that given
func (o *GetSecurityGroupInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get security group internal server error response
func (o *GetSecurityGroupInternalServerError) Code() int {
	return 500
}

func (o *GetSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSecurityGroupInternalServerError) String() string {
	return fmt.Sprintf("[GET /security-group/{secg}][%d] getSecurityGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSecurityGroupInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *GetSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
