// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListSecurityGroupParams creates a new ListSecurityGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSecurityGroupParams() *ListSecurityGroupParams {
	return &ListSecurityGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSecurityGroupParamsWithTimeout creates a new ListSecurityGroupParams object
// with the ability to set a timeout on a request.
func NewListSecurityGroupParamsWithTimeout(timeout time.Duration) *ListSecurityGroupParams {
	return &ListSecurityGroupParams{
		timeout: timeout,
	}
}

// NewListSecurityGroupParamsWithContext creates a new ListSecurityGroupParams object
// with the ability to set a context for a request.
func NewListSecurityGroupParamsWithContext(ctx context.Context) *ListSecurityGroupParams {
	return &ListSecurityGroupParams{
		Context: ctx,
	}
}

// NewListSecurityGroupParamsWithHTTPClient creates a new ListSecurityGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSecurityGroupParamsWithHTTPClient(client *http.Client) *ListSecurityGroupParams {
	return &ListSecurityGroupParams{
		HTTPClient: client,
	}
}

/*
ListSecurityGroupParams contains all the parameters to send to the API endpoint

	for the list security group operation.

	Typically these are written to a http.Request.
*/
type ListSecurityGroupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list security group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSecurityGroupParams) WithDefaults() *ListSecurityGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list security group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSecurityGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list security group params
func (o *ListSecurityGroupParams) WithTimeout(timeout time.Duration) *ListSecurityGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list security group params
func (o *ListSecurityGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list security group params
func (o *ListSecurityGroupParams) WithContext(ctx context.Context) *ListSecurityGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list security group params
func (o *ListSecurityGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list security group params
func (o *ListSecurityGroupParams) WithHTTPClient(client *http.Client) *ListSecurityGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list security group params
func (o *ListSecurityGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListSecurityGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
