// Code generated by go-swagger; DO NOT EDIT.

package smart_group_delegate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// ListSmartGroupDelegateReader is a Reader for the ListSmartGroupDelegate structure.
type ListSmartGroupDelegateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSmartGroupDelegateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSmartGroupDelegateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListSmartGroupDelegateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewListSmartGroupDelegateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListSmartGroupDelegateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSmartGroupDelegateOK creates a ListSmartGroupDelegateOK with default headers values
func NewListSmartGroupDelegateOK() *ListSmartGroupDelegateOK {
	return &ListSmartGroupDelegateOK{}
}

/*ListSmartGroupDelegateOK handles this case with default header values.

ok
*/
type ListSmartGroupDelegateOK struct {
	Payload []*vproxy_client_model.SmartGroupDelegate
}

func (o *ListSmartGroupDelegateOK) Error() string {
	return fmt.Sprintf("[GET /smart-group-delegate][%d] listSmartGroupDelegateOK  %+v", 200, o.Payload)
}

func (o *ListSmartGroupDelegateOK) GetPayload() []*vproxy_client_model.SmartGroupDelegate {
	return o.Payload
}

func (o *ListSmartGroupDelegateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSmartGroupDelegateBadRequest creates a ListSmartGroupDelegateBadRequest with default headers values
func NewListSmartGroupDelegateBadRequest() *ListSmartGroupDelegateBadRequest {
	return &ListSmartGroupDelegateBadRequest{}
}

/*ListSmartGroupDelegateBadRequest handles this case with default header values.

invalid input parameters
*/
type ListSmartGroupDelegateBadRequest struct {
	Payload *vproxy_client_model.Error400
}

func (o *ListSmartGroupDelegateBadRequest) Error() string {
	return fmt.Sprintf("[GET /smart-group-delegate][%d] listSmartGroupDelegateBadRequest  %+v", 400, o.Payload)
}

func (o *ListSmartGroupDelegateBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *ListSmartGroupDelegateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSmartGroupDelegateConflict creates a ListSmartGroupDelegateConflict with default headers values
func NewListSmartGroupDelegateConflict() *ListSmartGroupDelegateConflict {
	return &ListSmartGroupDelegateConflict{}
}

/*ListSmartGroupDelegateConflict handles this case with default header values.

conflict
*/
type ListSmartGroupDelegateConflict struct {
	Payload *vproxy_client_model.Error409
}

func (o *ListSmartGroupDelegateConflict) Error() string {
	return fmt.Sprintf("[GET /smart-group-delegate][%d] listSmartGroupDelegateConflict  %+v", 409, o.Payload)
}

func (o *ListSmartGroupDelegateConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *ListSmartGroupDelegateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSmartGroupDelegateInternalServerError creates a ListSmartGroupDelegateInternalServerError with default headers values
func NewListSmartGroupDelegateInternalServerError() *ListSmartGroupDelegateInternalServerError {
	return &ListSmartGroupDelegateInternalServerError{}
}

/*ListSmartGroupDelegateInternalServerError handles this case with default header values.

internal error
*/
type ListSmartGroupDelegateInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

func (o *ListSmartGroupDelegateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /smart-group-delegate][%d] listSmartGroupDelegateInternalServerError  %+v", 500, o.Payload)
}

func (o *ListSmartGroupDelegateInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *ListSmartGroupDelegateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
