# permissions for end users to view securitygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: securitygroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: securitygroup-viewer-role
rules:
- apiGroups:
  - app.vproxy.io
  resources:
  - securitygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.vproxy.io
  resources:
  - securitygroups/status
  verbs:
  - get
