# permissions for end users to edit servergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servergroup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: servergroup-editor-role
rules:
- apiGroups:
  - vproxy.io.vproxy.io
  resources:
  - servergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vproxy.io.vproxy.io
  resources:
  - servergroups/status
  verbs:
  - get
