# permissions for end users to edit socks5servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: socks5server-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: socks5server-editor-role
rules:
- apiGroups:
  - app.vproxy.io
  resources:
  - socks5servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.vproxy.io
  resources:
  - socks5servers/status
  verbs:
  - get
