# permissions for end users to view upstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upstream-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: upstream-viewer-role
rules:
- apiGroups:
  - vproxy.io.vproxy.io
  resources:
  - upstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vproxy.io.vproxy.io
  resources:
  - upstreams/status
  verbs:
  - get
