// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// GetSecurityGroupRuleReader is a Reader for the GetSecurityGroupRule structure.
type GetSecurityGroupRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSecurityGroupRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSecurityGroupRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSecurityGroupRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSecurityGroupRuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetSecurityGroupRuleConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSecurityGroupRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSecurityGroupRuleOK creates a GetSecurityGroupRuleOK with default headers values
func NewGetSecurityGroupRuleOK() *GetSecurityGroupRuleOK {
	return &GetSecurityGroupRuleOK{}
}

/*GetSecurityGroupRuleOK handles this case with default header values.

ok
*/
type GetSecurityGroupRuleOK struct {
	Payload *vproxy_client_model.SecurityGroupRule
}

func (o *GetSecurityGroupRuleOK) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}/security-group-rule/{secgr}][%d] getSecurityGroupRuleOK  %+v", 200, o.Payload)
}

func (o *GetSecurityGroupRuleOK) GetPayload() *vproxy_client_model.SecurityGroupRule {
	return o.Payload
}

func (o *GetSecurityGroupRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.SecurityGroupRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupRuleBadRequest creates a GetSecurityGroupRuleBadRequest with default headers values
func NewGetSecurityGroupRuleBadRequest() *GetSecurityGroupRuleBadRequest {
	return &GetSecurityGroupRuleBadRequest{}
}

/*GetSecurityGroupRuleBadRequest handles this case with default header values.

invalid input parameters
*/
type GetSecurityGroupRuleBadRequest struct {
	Payload *vproxy_client_model.Error400
}

func (o *GetSecurityGroupRuleBadRequest) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}/security-group-rule/{secgr}][%d] getSecurityGroupRuleBadRequest  %+v", 400, o.Payload)
}

func (o *GetSecurityGroupRuleBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *GetSecurityGroupRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupRuleNotFound creates a GetSecurityGroupRuleNotFound with default headers values
func NewGetSecurityGroupRuleNotFound() *GetSecurityGroupRuleNotFound {
	return &GetSecurityGroupRuleNotFound{}
}

/*GetSecurityGroupRuleNotFound handles this case with default header values.

resource not found
*/
type GetSecurityGroupRuleNotFound struct {
	Payload *vproxy_client_model.Error404
}

func (o *GetSecurityGroupRuleNotFound) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}/security-group-rule/{secgr}][%d] getSecurityGroupRuleNotFound  %+v", 404, o.Payload)
}

func (o *GetSecurityGroupRuleNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *GetSecurityGroupRuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupRuleConflict creates a GetSecurityGroupRuleConflict with default headers values
func NewGetSecurityGroupRuleConflict() *GetSecurityGroupRuleConflict {
	return &GetSecurityGroupRuleConflict{}
}

/*GetSecurityGroupRuleConflict handles this case with default header values.

conflict
*/
type GetSecurityGroupRuleConflict struct {
	Payload *vproxy_client_model.Error409
}

func (o *GetSecurityGroupRuleConflict) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}/security-group-rule/{secgr}][%d] getSecurityGroupRuleConflict  %+v", 409, o.Payload)
}

func (o *GetSecurityGroupRuleConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *GetSecurityGroupRuleConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupRuleInternalServerError creates a GetSecurityGroupRuleInternalServerError with default headers values
func NewGetSecurityGroupRuleInternalServerError() *GetSecurityGroupRuleInternalServerError {
	return &GetSecurityGroupRuleInternalServerError{}
}

/*GetSecurityGroupRuleInternalServerError handles this case with default header values.

internal error
*/
type GetSecurityGroupRuleInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

func (o *GetSecurityGroupRuleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /security-group/{secg}/security-group-rule/{secgr}][%d] getSecurityGroupRuleInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSecurityGroupRuleInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *GetSecurityGroupRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
