// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSecurityGroupRuleParams creates a new ListSecurityGroupRuleParams object
// with the default values initialized.
func NewListSecurityGroupRuleParams() *ListSecurityGroupRuleParams {
	var ()
	return &ListSecurityGroupRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSecurityGroupRuleParamsWithTimeout creates a new ListSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSecurityGroupRuleParamsWithTimeout(timeout time.Duration) *ListSecurityGroupRuleParams {
	var ()
	return &ListSecurityGroupRuleParams{

		timeout: timeout,
	}
}

// NewListSecurityGroupRuleParamsWithContext creates a new ListSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSecurityGroupRuleParamsWithContext(ctx context.Context) *ListSecurityGroupRuleParams {
	var ()
	return &ListSecurityGroupRuleParams{

		Context: ctx,
	}
}

// NewListSecurityGroupRuleParamsWithHTTPClient creates a new ListSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSecurityGroupRuleParamsWithHTTPClient(client *http.Client) *ListSecurityGroupRuleParams {
	var ()
	return &ListSecurityGroupRuleParams{
		HTTPClient: client,
	}
}

/*ListSecurityGroupRuleParams contains all the parameters to send to the API endpoint
for the list security group rule operation typically these are written to a http.Request
*/
type ListSecurityGroupRuleParams struct {

	/*Secg
	  name of the security-group

	*/
	Secg string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list security group rule params
func (o *ListSecurityGroupRuleParams) WithTimeout(timeout time.Duration) *ListSecurityGroupRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list security group rule params
func (o *ListSecurityGroupRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list security group rule params
func (o *ListSecurityGroupRuleParams) WithContext(ctx context.Context) *ListSecurityGroupRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list security group rule params
func (o *ListSecurityGroupRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list security group rule params
func (o *ListSecurityGroupRuleParams) WithHTTPClient(client *http.Client) *ListSecurityGroupRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list security group rule params
func (o *ListSecurityGroupRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSecg adds the secg to the list security group rule params
func (o *ListSecurityGroupRuleParams) WithSecg(secg string) *ListSecurityGroupRuleParams {
	o.SetSecg(secg)
	return o
}

// SetSecg adds the secg to the list security group rule params
func (o *ListSecurityGroupRuleParams) SetSecg(secg string) {
	o.Secg = secg
}

// WriteToRequest writes these params to a swagger request
func (o *ListSecurityGroupRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param secg
	if err := r.SetPathParam("secg", o.Secg); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
