// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddServerGroupReader is a Reader for the AddServerGroup structure.
type AddServerGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddServerGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAddServerGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddServerGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddServerGroupNoContent creates a AddServerGroupNoContent with default headers values
func NewAddServerGroupNoContent() *AddServerGroupNoContent {
	return &AddServerGroupNoContent{}
}

/*AddServerGroupNoContent handles this case with default header values.

ok
*/
type AddServerGroupNoContent struct {
}

func (o *AddServerGroupNoContent) Error() string {
	return fmt.Sprintf("[POST /server-group][%d] addServerGroupNoContent ", 204)
}

func (o *AddServerGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServerGroupBadRequest creates a AddServerGroupBadRequest with default headers values
func NewAddServerGroupBadRequest() *AddServerGroupBadRequest {
	return &AddServerGroupBadRequest{}
}

/*AddServerGroupBadRequest handles this case with default header values.

Invalid input
*/
type AddServerGroupBadRequest struct {
}

func (o *AddServerGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /server-group][%d] addServerGroupBadRequest ", 400)
}

func (o *AddServerGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
