// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServerGroupInUpstreamParams creates a new GetServerGroupInUpstreamParams object
// with the default values initialized.
func NewGetServerGroupInUpstreamParams() *GetServerGroupInUpstreamParams {
	var ()
	return &GetServerGroupInUpstreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServerGroupInUpstreamParamsWithTimeout creates a new GetServerGroupInUpstreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServerGroupInUpstreamParamsWithTimeout(timeout time.Duration) *GetServerGroupInUpstreamParams {
	var ()
	return &GetServerGroupInUpstreamParams{

		timeout: timeout,
	}
}

// NewGetServerGroupInUpstreamParamsWithContext creates a new GetServerGroupInUpstreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServerGroupInUpstreamParamsWithContext(ctx context.Context) *GetServerGroupInUpstreamParams {
	var ()
	return &GetServerGroupInUpstreamParams{

		Context: ctx,
	}
}

// NewGetServerGroupInUpstreamParamsWithHTTPClient creates a new GetServerGroupInUpstreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServerGroupInUpstreamParamsWithHTTPClient(client *http.Client) *GetServerGroupInUpstreamParams {
	var ()
	return &GetServerGroupInUpstreamParams{
		HTTPClient: client,
	}
}

/*GetServerGroupInUpstreamParams contains all the parameters to send to the API endpoint
for the get server group in upstream operation typically these are written to a http.Request
*/
type GetServerGroupInUpstreamParams struct {

	/*Sg
	  name of the server-group

	*/
	Sg string
	/*Ups
	  name of the upstream

	*/
	Ups string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) WithTimeout(timeout time.Duration) *GetServerGroupInUpstreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) WithContext(ctx context.Context) *GetServerGroupInUpstreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) WithHTTPClient(client *http.Client) *GetServerGroupInUpstreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSg adds the sg to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) WithSg(sg string) *GetServerGroupInUpstreamParams {
	o.SetSg(sg)
	return o
}

// SetSg adds the sg to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) SetSg(sg string) {
	o.Sg = sg
}

// WithUps adds the ups to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) WithUps(ups string) *GetServerGroupInUpstreamParams {
	o.SetUps(ups)
	return o
}

// SetUps adds the ups to the get server group in upstream params
func (o *GetServerGroupInUpstreamParams) SetUps(ups string) {
	o.Ups = ups
}

// WriteToRequest writes these params to a swagger request
func (o *GetServerGroupInUpstreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param sg
	if err := r.SetPathParam("sg", o.Sg); err != nil {
		return err
	}

	// path param ups
	if err := r.SetPathParam("ups", o.Ups); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
