// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// GetServerGroupReader is a Reader for the GetServerGroup structure.
type GetServerGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServerGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServerGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetServerGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServerGroupOK creates a GetServerGroupOK with default headers values
func NewGetServerGroupOK() *GetServerGroupOK {
	return &GetServerGroupOK{}
}

/*GetServerGroupOK handles this case with default header values.

ok
*/
type GetServerGroupOK struct {
	Payload *vproxy_client_model.ServerGroup
}

func (o *GetServerGroupOK) Error() string {
	return fmt.Sprintf("[GET /server-group/{sg}][%d] getServerGroupOK  %+v", 200, o.Payload)
}

func (o *GetServerGroupOK) GetPayload() *vproxy_client_model.ServerGroup {
	return o.Payload
}

func (o *GetServerGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.ServerGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServerGroupNotFound creates a GetServerGroupNotFound with default headers values
func NewGetServerGroupNotFound() *GetServerGroupNotFound {
	return &GetServerGroupNotFound{}
}

/*GetServerGroupNotFound handles this case with default header values.

not found
*/
type GetServerGroupNotFound struct {
}

func (o *GetServerGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /server-group/{sg}][%d] getServerGroupNotFound ", 404)
}

func (o *GetServerGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
