// Code generated by go-swagger; DO NOT EDIT.

package server_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// ListServerGroupInUpstreamReader is a Reader for the ListServerGroupInUpstream structure.
type ListServerGroupInUpstreamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServerGroupInUpstreamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListServerGroupInUpstreamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListServerGroupInUpstreamOK creates a ListServerGroupInUpstreamOK with default headers values
func NewListServerGroupInUpstreamOK() *ListServerGroupInUpstreamOK {
	return &ListServerGroupInUpstreamOK{}
}

/*ListServerGroupInUpstreamOK handles this case with default header values.

ok
*/
type ListServerGroupInUpstreamOK struct {
	Payload []*vproxy_client_model.ServerGroupInUpstream
}

func (o *ListServerGroupInUpstreamOK) Error() string {
	return fmt.Sprintf("[GET /upstream/{ups}/server-group][%d] listServerGroupInUpstreamOK  %+v", 200, o.Payload)
}

func (o *ListServerGroupInUpstreamOK) GetPayload() []*vproxy_client_model.ServerGroupInUpstream {
	return o.Payload
}

func (o *ListServerGroupInUpstreamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
