// Code generated by go-swagger; DO NOT EDIT.

package dns_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// GetDNSServerReader is a Reader for the GetDNSServer structure.
type GetDNSServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDNSServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDNSServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDNSServerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDNSServerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetDNSServerConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDNSServerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDNSServerOK creates a GetDNSServerOK with default headers values
func NewGetDNSServerOK() *GetDNSServerOK {
	return &GetDNSServerOK{}
}

/*
GetDNSServerOK describes a response with status code 200, with default header values.

ok
*/
type GetDNSServerOK struct {
	Payload *vproxy_client_model.DNSServer
}

// IsSuccess returns true when this get Dns server o k response has a 2xx status code
func (o *GetDNSServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Dns server o k response has a 3xx status code
func (o *GetDNSServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server o k response has a 4xx status code
func (o *GetDNSServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Dns server o k response has a 5xx status code
func (o *GetDNSServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server o k response a status code equal to that given
func (o *GetDNSServerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Dns server o k response
func (o *GetDNSServerOK) Code() int {
	return 200
}

func (o *GetDNSServerOK) Error() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerOK  %+v", 200, o.Payload)
}

func (o *GetDNSServerOK) String() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerOK  %+v", 200, o.Payload)
}

func (o *GetDNSServerOK) GetPayload() *vproxy_client_model.DNSServer {
	return o.Payload
}

func (o *GetDNSServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.DNSServer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSServerBadRequest creates a GetDNSServerBadRequest with default headers values
func NewGetDNSServerBadRequest() *GetDNSServerBadRequest {
	return &GetDNSServerBadRequest{}
}

/*
GetDNSServerBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type GetDNSServerBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this get Dns server bad request response has a 2xx status code
func (o *GetDNSServerBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Dns server bad request response has a 3xx status code
func (o *GetDNSServerBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server bad request response has a 4xx status code
func (o *GetDNSServerBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Dns server bad request response has a 5xx status code
func (o *GetDNSServerBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server bad request response a status code equal to that given
func (o *GetDNSServerBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Dns server bad request response
func (o *GetDNSServerBadRequest) Code() int {
	return 400
}

func (o *GetDNSServerBadRequest) Error() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerBadRequest  %+v", 400, o.Payload)
}

func (o *GetDNSServerBadRequest) String() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerBadRequest  %+v", 400, o.Payload)
}

func (o *GetDNSServerBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *GetDNSServerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSServerNotFound creates a GetDNSServerNotFound with default headers values
func NewGetDNSServerNotFound() *GetDNSServerNotFound {
	return &GetDNSServerNotFound{}
}

/*
GetDNSServerNotFound describes a response with status code 404, with default header values.

resource not found
*/
type GetDNSServerNotFound struct {
	Payload *vproxy_client_model.Error404
}

// IsSuccess returns true when this get Dns server not found response has a 2xx status code
func (o *GetDNSServerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Dns server not found response has a 3xx status code
func (o *GetDNSServerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server not found response has a 4xx status code
func (o *GetDNSServerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Dns server not found response has a 5xx status code
func (o *GetDNSServerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server not found response a status code equal to that given
func (o *GetDNSServerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Dns server not found response
func (o *GetDNSServerNotFound) Code() int {
	return 404
}

func (o *GetDNSServerNotFound) Error() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerNotFound  %+v", 404, o.Payload)
}

func (o *GetDNSServerNotFound) String() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerNotFound  %+v", 404, o.Payload)
}

func (o *GetDNSServerNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *GetDNSServerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSServerConflict creates a GetDNSServerConflict with default headers values
func NewGetDNSServerConflict() *GetDNSServerConflict {
	return &GetDNSServerConflict{}
}

/*
GetDNSServerConflict describes a response with status code 409, with default header values.

conflict
*/
type GetDNSServerConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this get Dns server conflict response has a 2xx status code
func (o *GetDNSServerConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Dns server conflict response has a 3xx status code
func (o *GetDNSServerConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server conflict response has a 4xx status code
func (o *GetDNSServerConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Dns server conflict response has a 5xx status code
func (o *GetDNSServerConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server conflict response a status code equal to that given
func (o *GetDNSServerConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get Dns server conflict response
func (o *GetDNSServerConflict) Code() int {
	return 409
}

func (o *GetDNSServerConflict) Error() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerConflict  %+v", 409, o.Payload)
}

func (o *GetDNSServerConflict) String() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerConflict  %+v", 409, o.Payload)
}

func (o *GetDNSServerConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *GetDNSServerConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSServerInternalServerError creates a GetDNSServerInternalServerError with default headers values
func NewGetDNSServerInternalServerError() *GetDNSServerInternalServerError {
	return &GetDNSServerInternalServerError{}
}

/*
GetDNSServerInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type GetDNSServerInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this get Dns server internal server error response has a 2xx status code
func (o *GetDNSServerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Dns server internal server error response has a 3xx status code
func (o *GetDNSServerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server internal server error response has a 4xx status code
func (o *GetDNSServerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Dns server internal server error response has a 5xx status code
func (o *GetDNSServerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Dns server internal server error response a status code equal to that given
func (o *GetDNSServerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Dns server internal server error response
func (o *GetDNSServerInternalServerError) Code() int {
	return 500
}

func (o *GetDNSServerInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDNSServerInternalServerError) String() string {
	return fmt.Sprintf("[GET /dns-server/{dns}][%d] getDnsServerInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDNSServerInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *GetDNSServerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
