// Code generated by go-swagger; DO NOT EDIT.

package dns_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveDNSServerParams creates a new RemoveDNSServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveDNSServerParams() *RemoveDNSServerParams {
	return &RemoveDNSServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveDNSServerParamsWithTimeout creates a new RemoveDNSServerParams object
// with the ability to set a timeout on a request.
func NewRemoveDNSServerParamsWithTimeout(timeout time.Duration) *RemoveDNSServerParams {
	return &RemoveDNSServerParams{
		timeout: timeout,
	}
}

// NewRemoveDNSServerParamsWithContext creates a new RemoveDNSServerParams object
// with the ability to set a context for a request.
func NewRemoveDNSServerParamsWithContext(ctx context.Context) *RemoveDNSServerParams {
	return &RemoveDNSServerParams{
		Context: ctx,
	}
}

// NewRemoveDNSServerParamsWithHTTPClient creates a new RemoveDNSServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveDNSServerParamsWithHTTPClient(client *http.Client) *RemoveDNSServerParams {
	return &RemoveDNSServerParams{
		HTTPClient: client,
	}
}

/*
RemoveDNSServerParams contains all the parameters to send to the API endpoint

	for the remove Dns server operation.

	Typically these are written to a http.Request.
*/
type RemoveDNSServerParams struct {

	/* DNS.

	   name of the dns-server
	*/
	DNS string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove Dns server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDNSServerParams) WithDefaults() *RemoveDNSServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove Dns server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDNSServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove Dns server params
func (o *RemoveDNSServerParams) WithTimeout(timeout time.Duration) *RemoveDNSServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove Dns server params
func (o *RemoveDNSServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove Dns server params
func (o *RemoveDNSServerParams) WithContext(ctx context.Context) *RemoveDNSServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove Dns server params
func (o *RemoveDNSServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove Dns server params
func (o *RemoveDNSServerParams) WithHTTPClient(client *http.Client) *RemoveDNSServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove Dns server params
func (o *RemoveDNSServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDNS adds the dns to the remove Dns server params
func (o *RemoveDNSServerParams) WithDNS(dns string) *RemoveDNSServerParams {
	o.SetDNS(dns)
	return o
}

// SetDNS adds the dns to the remove Dns server params
func (o *RemoveDNSServerParams) SetDNS(dns string) {
	o.DNS = dns
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveDNSServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dns
	if err := r.SetPathParam("dns", o.DNS); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
