// Code generated by go-swagger; DO NOT EDIT.

package smart_node_delegate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// NewAddSmartNodeDelegateParams creates a new AddSmartNodeDelegateParams object
// with the default values initialized.
func NewAddSmartNodeDelegateParams() *AddSmartNodeDelegateParams {
	var ()
	return &AddSmartNodeDelegateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddSmartNodeDelegateParamsWithTimeout creates a new AddSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddSmartNodeDelegateParamsWithTimeout(timeout time.Duration) *AddSmartNodeDelegateParams {
	var ()
	return &AddSmartNodeDelegateParams{

		timeout: timeout,
	}
}

// NewAddSmartNodeDelegateParamsWithContext creates a new AddSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddSmartNodeDelegateParamsWithContext(ctx context.Context) *AddSmartNodeDelegateParams {
	var ()
	return &AddSmartNodeDelegateParams{

		Context: ctx,
	}
}

// NewAddSmartNodeDelegateParamsWithHTTPClient creates a new AddSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddSmartNodeDelegateParamsWithHTTPClient(client *http.Client) *AddSmartNodeDelegateParams {
	var ()
	return &AddSmartNodeDelegateParams{
		HTTPClient: client,
	}
}

/*AddSmartNodeDelegateParams contains all the parameters to send to the API endpoint
for the add smart node delegate operation typically these are written to a http.Request
*/
type AddSmartNodeDelegateParams struct {

	/*Body*/
	Body *vproxy_client_model.SmartNodeDelegateCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) WithTimeout(timeout time.Duration) *AddSmartNodeDelegateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) WithContext(ctx context.Context) *AddSmartNodeDelegateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) WithHTTPClient(client *http.Client) *AddSmartNodeDelegateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) WithBody(body *vproxy_client_model.SmartNodeDelegateCreate) *AddSmartNodeDelegateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add smart node delegate params
func (o *AddSmartNodeDelegateParams) SetBody(body *vproxy_client_model.SmartNodeDelegateCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddSmartNodeDelegateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
