// Code generated by go-swagger; DO NOT EDIT.

package smart_node_delegate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeSmartNodeDelegateParams creates a new DescribeSmartNodeDelegateParams object
// with the default values initialized.
func NewDescribeSmartNodeDelegateParams() *DescribeSmartNodeDelegateParams {
	var ()
	return &DescribeSmartNodeDelegateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeSmartNodeDelegateParamsWithTimeout creates a new DescribeSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeSmartNodeDelegateParamsWithTimeout(timeout time.Duration) *DescribeSmartNodeDelegateParams {
	var ()
	return &DescribeSmartNodeDelegateParams{

		timeout: timeout,
	}
}

// NewDescribeSmartNodeDelegateParamsWithContext creates a new DescribeSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeSmartNodeDelegateParamsWithContext(ctx context.Context) *DescribeSmartNodeDelegateParams {
	var ()
	return &DescribeSmartNodeDelegateParams{

		Context: ctx,
	}
}

// NewDescribeSmartNodeDelegateParamsWithHTTPClient creates a new DescribeSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeSmartNodeDelegateParamsWithHTTPClient(client *http.Client) *DescribeSmartNodeDelegateParams {
	var ()
	return &DescribeSmartNodeDelegateParams{
		HTTPClient: client,
	}
}

/*DescribeSmartNodeDelegateParams contains all the parameters to send to the API endpoint
for the describe smart node delegate operation typically these are written to a http.Request
*/
type DescribeSmartNodeDelegateParams struct {

	/*Snd
	  name of the smart-node-delegate

	*/
	Snd string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) WithTimeout(timeout time.Duration) *DescribeSmartNodeDelegateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) WithContext(ctx context.Context) *DescribeSmartNodeDelegateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) WithHTTPClient(client *http.Client) *DescribeSmartNodeDelegateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSnd adds the snd to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) WithSnd(snd string) *DescribeSmartNodeDelegateParams {
	o.SetSnd(snd)
	return o
}

// SetSnd adds the snd to the describe smart node delegate params
func (o *DescribeSmartNodeDelegateParams) SetSnd(snd string) {
	o.Snd = snd
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeSmartNodeDelegateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param snd
	if err := r.SetPathParam("snd", o.Snd); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
