// Code generated by go-swagger; DO NOT EDIT.

package smart_node_delegate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemoveSmartNodeDelegateParams creates a new RemoveSmartNodeDelegateParams object
// with the default values initialized.
func NewRemoveSmartNodeDelegateParams() *RemoveSmartNodeDelegateParams {
	var ()
	return &RemoveSmartNodeDelegateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveSmartNodeDelegateParamsWithTimeout creates a new RemoveSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveSmartNodeDelegateParamsWithTimeout(timeout time.Duration) *RemoveSmartNodeDelegateParams {
	var ()
	return &RemoveSmartNodeDelegateParams{

		timeout: timeout,
	}
}

// NewRemoveSmartNodeDelegateParamsWithContext creates a new RemoveSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveSmartNodeDelegateParamsWithContext(ctx context.Context) *RemoveSmartNodeDelegateParams {
	var ()
	return &RemoveSmartNodeDelegateParams{

		Context: ctx,
	}
}

// NewRemoveSmartNodeDelegateParamsWithHTTPClient creates a new RemoveSmartNodeDelegateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveSmartNodeDelegateParamsWithHTTPClient(client *http.Client) *RemoveSmartNodeDelegateParams {
	var ()
	return &RemoveSmartNodeDelegateParams{
		HTTPClient: client,
	}
}

/*RemoveSmartNodeDelegateParams contains all the parameters to send to the API endpoint
for the remove smart node delegate operation typically these are written to a http.Request
*/
type RemoveSmartNodeDelegateParams struct {

	/*Snd
	  name of the smart-node-delegate

	*/
	Snd string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) WithTimeout(timeout time.Duration) *RemoveSmartNodeDelegateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) WithContext(ctx context.Context) *RemoveSmartNodeDelegateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) WithHTTPClient(client *http.Client) *RemoveSmartNodeDelegateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSnd adds the snd to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) WithSnd(snd string) *RemoveSmartNodeDelegateParams {
	o.SetSnd(snd)
	return o
}

// SetSnd adds the snd to the remove smart node delegate params
func (o *RemoveSmartNodeDelegateParams) SetSnd(snd string) {
	o.Snd = snd
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveSmartNodeDelegateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param snd
	if err := r.SetPathParam("snd", o.Snd); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
