// Code generated by go-swagger; DO NOT EDIT.

package event_loop

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// DescribeEventLoopReader is a Reader for the DescribeEventLoop structure.
type DescribeEventLoopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeEventLoopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeEventLoopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDescribeEventLoopNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeEventLoopOK creates a DescribeEventLoopOK with default headers values
func NewDescribeEventLoopOK() *DescribeEventLoopOK {
	return &DescribeEventLoopOK{}
}

/*DescribeEventLoopOK handles this case with default header values.

ok
*/
type DescribeEventLoopOK struct {
	Payload *vproxy_client_model.EventLoopDetail
}

func (o *DescribeEventLoopOK) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}/detail][%d] describeEventLoopOK  %+v", 200, o.Payload)
}

func (o *DescribeEventLoopOK) GetPayload() *vproxy_client_model.EventLoopDetail {
	return o.Payload
}

func (o *DescribeEventLoopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.EventLoopDetail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeEventLoopNotFound creates a DescribeEventLoopNotFound with default headers values
func NewDescribeEventLoopNotFound() *DescribeEventLoopNotFound {
	return &DescribeEventLoopNotFound{}
}

/*DescribeEventLoopNotFound handles this case with default header values.

not found
*/
type DescribeEventLoopNotFound struct {
}

func (o *DescribeEventLoopNotFound) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}/detail][%d] describeEventLoopNotFound ", 404)
}

func (o *DescribeEventLoopNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
