// Code generated by go-swagger; DO NOT EDIT.

package event_loop

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListEventLoopParams creates a new ListEventLoopParams object
// with the default values initialized.
func NewListEventLoopParams() *ListEventLoopParams {
	var ()
	return &ListEventLoopParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListEventLoopParamsWithTimeout creates a new ListEventLoopParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListEventLoopParamsWithTimeout(timeout time.Duration) *ListEventLoopParams {
	var ()
	return &ListEventLoopParams{

		timeout: timeout,
	}
}

// NewListEventLoopParamsWithContext creates a new ListEventLoopParams object
// with the default values initialized, and the ability to set a context for a request
func NewListEventLoopParamsWithContext(ctx context.Context) *ListEventLoopParams {
	var ()
	return &ListEventLoopParams{

		Context: ctx,
	}
}

// NewListEventLoopParamsWithHTTPClient creates a new ListEventLoopParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListEventLoopParamsWithHTTPClient(client *http.Client) *ListEventLoopParams {
	var ()
	return &ListEventLoopParams{
		HTTPClient: client,
	}
}

/*ListEventLoopParams contains all the parameters to send to the API endpoint
for the list event loop operation typically these are written to a http.Request
*/
type ListEventLoopParams struct {

	/*Elg
	  name of the event-loop-group

	*/
	Elg string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list event loop params
func (o *ListEventLoopParams) WithTimeout(timeout time.Duration) *ListEventLoopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list event loop params
func (o *ListEventLoopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list event loop params
func (o *ListEventLoopParams) WithContext(ctx context.Context) *ListEventLoopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list event loop params
func (o *ListEventLoopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list event loop params
func (o *ListEventLoopParams) WithHTTPClient(client *http.Client) *ListEventLoopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list event loop params
func (o *ListEventLoopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithElg adds the elg to the list event loop params
func (o *ListEventLoopParams) WithElg(elg string) *ListEventLoopParams {
	o.SetElg(elg)
	return o
}

// SetElg adds the elg to the list event loop params
func (o *ListEventLoopParams) SetElg(elg string) {
	o.Elg = elg
}

// WriteToRequest writes these params to a swagger request
func (o *ListEventLoopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param elg
	if err := r.SetPathParam("elg", o.Elg); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
