// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateSecurityGroupReader is a Reader for the UpdateSecurityGroup structure.
type UpdateSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateSecurityGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateSecurityGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSecurityGroupNoContent creates a UpdateSecurityGroupNoContent with default headers values
func NewUpdateSecurityGroupNoContent() *UpdateSecurityGroupNoContent {
	return &UpdateSecurityGroupNoContent{}
}

/*UpdateSecurityGroupNoContent handles this case with default header values.

ok
*/
type UpdateSecurityGroupNoContent struct {
}

func (o *UpdateSecurityGroupNoContent) Error() string {
	return fmt.Sprintf("[PUT /security-group/{secg}][%d] updateSecurityGroupNoContent ", 204)
}

func (o *UpdateSecurityGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSecurityGroupBadRequest creates a UpdateSecurityGroupBadRequest with default headers values
func NewUpdateSecurityGroupBadRequest() *UpdateSecurityGroupBadRequest {
	return &UpdateSecurityGroupBadRequest{}
}

/*UpdateSecurityGroupBadRequest handles this case with default header values.

Invalid input
*/
type UpdateSecurityGroupBadRequest struct {
}

func (o *UpdateSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[PUT /security-group/{secg}][%d] updateSecurityGroupBadRequest ", 400)
}

func (o *UpdateSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSecurityGroupNotFound creates a UpdateSecurityGroupNotFound with default headers values
func NewUpdateSecurityGroupNotFound() *UpdateSecurityGroupNotFound {
	return &UpdateSecurityGroupNotFound{}
}

/*UpdateSecurityGroupNotFound handles this case with default header values.

SecurityGroup not found
*/
type UpdateSecurityGroupNotFound struct {
}

func (o *UpdateSecurityGroupNotFound) Error() string {
	return fmt.Sprintf("[PUT /security-group/{secg}][%d] updateSecurityGroupNotFound ", 404)
}

func (o *UpdateSecurityGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
