// Code generated by go-swagger; DO NOT EDIT.

package socks5_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// ListSocks5ServerReader is a Reader for the ListSocks5Server structure.
type ListSocks5ServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSocks5ServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSocks5ServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSocks5ServerOK creates a ListSocks5ServerOK with default headers values
func NewListSocks5ServerOK() *ListSocks5ServerOK {
	return &ListSocks5ServerOK{}
}

/*ListSocks5ServerOK handles this case with default header values.

ok
*/
type ListSocks5ServerOK struct {
	Payload []*vproxy_client_model.Socks5Server
}

func (o *ListSocks5ServerOK) Error() string {
	return fmt.Sprintf("[GET /socks5-server][%d] listSocks5ServerOK  %+v", 200, o.Payload)
}

func (o *ListSocks5ServerOK) GetPayload() []*vproxy_client_model.Socks5Server {
	return o.Payload
}

func (o *ListSocks5ServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
