// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// NewAddSecurityGroupRuleParams creates a new AddSecurityGroupRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddSecurityGroupRuleParams() *AddSecurityGroupRuleParams {
	return &AddSecurityGroupRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddSecurityGroupRuleParamsWithTimeout creates a new AddSecurityGroupRuleParams object
// with the ability to set a timeout on a request.
func NewAddSecurityGroupRuleParamsWithTimeout(timeout time.Duration) *AddSecurityGroupRuleParams {
	return &AddSecurityGroupRuleParams{
		timeout: timeout,
	}
}

// NewAddSecurityGroupRuleParamsWithContext creates a new AddSecurityGroupRuleParams object
// with the ability to set a context for a request.
func NewAddSecurityGroupRuleParamsWithContext(ctx context.Context) *AddSecurityGroupRuleParams {
	return &AddSecurityGroupRuleParams{
		Context: ctx,
	}
}

// NewAddSecurityGroupRuleParamsWithHTTPClient creates a new AddSecurityGroupRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddSecurityGroupRuleParamsWithHTTPClient(client *http.Client) *AddSecurityGroupRuleParams {
	return &AddSecurityGroupRuleParams{
		HTTPClient: client,
	}
}

/*
AddSecurityGroupRuleParams contains all the parameters to send to the API endpoint

	for the add security group rule operation.

	Typically these are written to a http.Request.
*/
type AddSecurityGroupRuleParams struct {

	// Body.
	Body *vproxy_client_model.SecurityGroupRuleCreate

	/* Secg.

	   name of the security-group
	*/
	Secg string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add security group rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSecurityGroupRuleParams) WithDefaults() *AddSecurityGroupRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add security group rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSecurityGroupRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add security group rule params
func (o *AddSecurityGroupRuleParams) WithTimeout(timeout time.Duration) *AddSecurityGroupRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add security group rule params
func (o *AddSecurityGroupRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add security group rule params
func (o *AddSecurityGroupRuleParams) WithContext(ctx context.Context) *AddSecurityGroupRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add security group rule params
func (o *AddSecurityGroupRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add security group rule params
func (o *AddSecurityGroupRuleParams) WithHTTPClient(client *http.Client) *AddSecurityGroupRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add security group rule params
func (o *AddSecurityGroupRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add security group rule params
func (o *AddSecurityGroupRuleParams) WithBody(body *vproxy_client_model.SecurityGroupRuleCreate) *AddSecurityGroupRuleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add security group rule params
func (o *AddSecurityGroupRuleParams) SetBody(body *vproxy_client_model.SecurityGroupRuleCreate) {
	o.Body = body
}

// WithSecg adds the secg to the add security group rule params
func (o *AddSecurityGroupRuleParams) WithSecg(secg string) *AddSecurityGroupRuleParams {
	o.SetSecg(secg)
	return o
}

// SetSecg adds the secg to the add security group rule params
func (o *AddSecurityGroupRuleParams) SetSecg(secg string) {
	o.Secg = secg
}

// WriteToRequest writes these params to a swagger request
func (o *AddSecurityGroupRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param secg
	if err := r.SetPathParam("secg", o.Secg); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
