// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeSecurityGroupRuleParams creates a new DescribeSecurityGroupRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeSecurityGroupRuleParams() *DescribeSecurityGroupRuleParams {
	return &DescribeSecurityGroupRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeSecurityGroupRuleParamsWithTimeout creates a new DescribeSecurityGroupRuleParams object
// with the ability to set a timeout on a request.
func NewDescribeSecurityGroupRuleParamsWithTimeout(timeout time.Duration) *DescribeSecurityGroupRuleParams {
	return &DescribeSecurityGroupRuleParams{
		timeout: timeout,
	}
}

// NewDescribeSecurityGroupRuleParamsWithContext creates a new DescribeSecurityGroupRuleParams object
// with the ability to set a context for a request.
func NewDescribeSecurityGroupRuleParamsWithContext(ctx context.Context) *DescribeSecurityGroupRuleParams {
	return &DescribeSecurityGroupRuleParams{
		Context: ctx,
	}
}

// NewDescribeSecurityGroupRuleParamsWithHTTPClient creates a new DescribeSecurityGroupRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeSecurityGroupRuleParamsWithHTTPClient(client *http.Client) *DescribeSecurityGroupRuleParams {
	return &DescribeSecurityGroupRuleParams{
		HTTPClient: client,
	}
}

/*
DescribeSecurityGroupRuleParams contains all the parameters to send to the API endpoint

	for the describe security group rule operation.

	Typically these are written to a http.Request.
*/
type DescribeSecurityGroupRuleParams struct {

	/* Secg.

	   name of the security-group
	*/
	Secg string

	/* Secgr.

	   name of the security-group-rule
	*/
	Secgr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the describe security group rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeSecurityGroupRuleParams) WithDefaults() *DescribeSecurityGroupRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe security group rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeSecurityGroupRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) WithTimeout(timeout time.Duration) *DescribeSecurityGroupRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) WithContext(ctx context.Context) *DescribeSecurityGroupRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) WithHTTPClient(client *http.Client) *DescribeSecurityGroupRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSecg adds the secg to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) WithSecg(secg string) *DescribeSecurityGroupRuleParams {
	o.SetSecg(secg)
	return o
}

// SetSecg adds the secg to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) SetSecg(secg string) {
	o.Secg = secg
}

// WithSecgr adds the secgr to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) WithSecgr(secgr string) *DescribeSecurityGroupRuleParams {
	o.SetSecgr(secgr)
	return o
}

// SetSecgr adds the secgr to the describe security group rule params
func (o *DescribeSecurityGroupRuleParams) SetSecgr(secgr string) {
	o.Secgr = secgr
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeSecurityGroupRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param secg
	if err := r.SetPathParam("secg", o.Secg); err != nil {
		return err
	}

	// path param secgr
	if err := r.SetPathParam("secgr", o.Secgr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
