// Code generated by go-swagger; DO NOT EDIT.

package cert_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	vproxy_client_model "vproxy_client_model"
)

// NewAddCertKeyParams creates a new AddCertKeyParams object
// with the default values initialized.
func NewAddCertKeyParams() *AddCertKeyParams {
	var ()
	return &AddCertKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddCertKeyParamsWithTimeout creates a new AddCertKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddCertKeyParamsWithTimeout(timeout time.Duration) *AddCertKeyParams {
	var ()
	return &AddCertKeyParams{

		timeout: timeout,
	}
}

// NewAddCertKeyParamsWithContext creates a new AddCertKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddCertKeyParamsWithContext(ctx context.Context) *AddCertKeyParams {
	var ()
	return &AddCertKeyParams{

		Context: ctx,
	}
}

// NewAddCertKeyParamsWithHTTPClient creates a new AddCertKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddCertKeyParamsWithHTTPClient(client *http.Client) *AddCertKeyParams {
	var ()
	return &AddCertKeyParams{
		HTTPClient: client,
	}
}

/*AddCertKeyParams contains all the parameters to send to the API endpoint
for the add cert key operation typically these are written to a http.Request
*/
type AddCertKeyParams struct {

	/*Body*/
	Body *vproxy_client_model.CertKeyCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add cert key params
func (o *AddCertKeyParams) WithTimeout(timeout time.Duration) *AddCertKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add cert key params
func (o *AddCertKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add cert key params
func (o *AddCertKeyParams) WithContext(ctx context.Context) *AddCertKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add cert key params
func (o *AddCertKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add cert key params
func (o *AddCertKeyParams) WithHTTPClient(client *http.Client) *AddCertKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add cert key params
func (o *AddCertKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add cert key params
func (o *AddCertKeyParams) WithBody(body *vproxy_client_model.CertKeyCreate) *AddCertKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add cert key params
func (o *AddCertKeyParams) SetBody(body *vproxy_client_model.CertKeyCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddCertKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
