// Code generated by go-swagger; DO NOT EDIT.

package vproxy_client_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventLoopGroup event loop group
//
// swagger:model EventLoopGroup
type EventLoopGroup struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this event loop group
func (m *EventLoopGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event loop group based on context it is used
func (m *EventLoopGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventLoopGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventLoopGroup) UnmarshalBinary(b []byte) error {
	var res EventLoopGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
