// Code generated by go-swagger; DO NOT EDIT.

package tcp_lb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// ListTCPLbReader is a Reader for the ListTCPLb structure.
type ListTCPLbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTCPLbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTCPLbOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListTCPLbBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewListTCPLbConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListTCPLbInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTCPLbOK creates a ListTCPLbOK with default headers values
func NewListTCPLbOK() *ListTCPLbOK {
	return &ListTCPLbOK{}
}

/*
ListTCPLbOK describes a response with status code 200, with default header values.

ok
*/
type ListTCPLbOK struct {
	Payload []*vproxy_client_model.TCPLb
}

// IsSuccess returns true when this list Tcp lb o k response has a 2xx status code
func (o *ListTCPLbOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Tcp lb o k response has a 3xx status code
func (o *ListTCPLbOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Tcp lb o k response has a 4xx status code
func (o *ListTCPLbOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Tcp lb o k response has a 5xx status code
func (o *ListTCPLbOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Tcp lb o k response a status code equal to that given
func (o *ListTCPLbOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Tcp lb o k response
func (o *ListTCPLbOK) Code() int {
	return 200
}

func (o *ListTCPLbOK) Error() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbOK  %+v", 200, o.Payload)
}

func (o *ListTCPLbOK) String() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbOK  %+v", 200, o.Payload)
}

func (o *ListTCPLbOK) GetPayload() []*vproxy_client_model.TCPLb {
	return o.Payload
}

func (o *ListTCPLbOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTCPLbBadRequest creates a ListTCPLbBadRequest with default headers values
func NewListTCPLbBadRequest() *ListTCPLbBadRequest {
	return &ListTCPLbBadRequest{}
}

/*
ListTCPLbBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type ListTCPLbBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this list Tcp lb bad request response has a 2xx status code
func (o *ListTCPLbBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Tcp lb bad request response has a 3xx status code
func (o *ListTCPLbBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Tcp lb bad request response has a 4xx status code
func (o *ListTCPLbBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Tcp lb bad request response has a 5xx status code
func (o *ListTCPLbBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list Tcp lb bad request response a status code equal to that given
func (o *ListTCPLbBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list Tcp lb bad request response
func (o *ListTCPLbBadRequest) Code() int {
	return 400
}

func (o *ListTCPLbBadRequest) Error() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbBadRequest  %+v", 400, o.Payload)
}

func (o *ListTCPLbBadRequest) String() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbBadRequest  %+v", 400, o.Payload)
}

func (o *ListTCPLbBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *ListTCPLbBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTCPLbConflict creates a ListTCPLbConflict with default headers values
func NewListTCPLbConflict() *ListTCPLbConflict {
	return &ListTCPLbConflict{}
}

/*
ListTCPLbConflict describes a response with status code 409, with default header values.

conflict
*/
type ListTCPLbConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this list Tcp lb conflict response has a 2xx status code
func (o *ListTCPLbConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Tcp lb conflict response has a 3xx status code
func (o *ListTCPLbConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Tcp lb conflict response has a 4xx status code
func (o *ListTCPLbConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Tcp lb conflict response has a 5xx status code
func (o *ListTCPLbConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this list Tcp lb conflict response a status code equal to that given
func (o *ListTCPLbConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the list Tcp lb conflict response
func (o *ListTCPLbConflict) Code() int {
	return 409
}

func (o *ListTCPLbConflict) Error() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbConflict  %+v", 409, o.Payload)
}

func (o *ListTCPLbConflict) String() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbConflict  %+v", 409, o.Payload)
}

func (o *ListTCPLbConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *ListTCPLbConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTCPLbInternalServerError creates a ListTCPLbInternalServerError with default headers values
func NewListTCPLbInternalServerError() *ListTCPLbInternalServerError {
	return &ListTCPLbInternalServerError{}
}

/*
ListTCPLbInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type ListTCPLbInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this list Tcp lb internal server error response has a 2xx status code
func (o *ListTCPLbInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Tcp lb internal server error response has a 3xx status code
func (o *ListTCPLbInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Tcp lb internal server error response has a 4xx status code
func (o *ListTCPLbInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Tcp lb internal server error response has a 5xx status code
func (o *ListTCPLbInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list Tcp lb internal server error response a status code equal to that given
func (o *ListTCPLbInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list Tcp lb internal server error response
func (o *ListTCPLbInternalServerError) Code() int {
	return 500
}

func (o *ListTCPLbInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbInternalServerError  %+v", 500, o.Payload)
}

func (o *ListTCPLbInternalServerError) String() string {
	return fmt.Sprintf("[GET /tcp-lb][%d] listTcpLbInternalServerError  %+v", 500, o.Payload)
}

func (o *ListTCPLbInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *ListTCPLbInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
