// Code generated by go-swagger; DO NOT EDIT.

package event_loop

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vproxy-tools/vpctl/swagger/vproxy_client_model"
)

// GetEventLoopReader is a Reader for the GetEventLoop structure.
type GetEventLoopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEventLoopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEventLoopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEventLoopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetEventLoopNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetEventLoopConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetEventLoopInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEventLoopOK creates a GetEventLoopOK with default headers values
func NewGetEventLoopOK() *GetEventLoopOK {
	return &GetEventLoopOK{}
}

/*
GetEventLoopOK describes a response with status code 200, with default header values.

ok
*/
type GetEventLoopOK struct {
	Payload *vproxy_client_model.EventLoop
}

// IsSuccess returns true when this get event loop o k response has a 2xx status code
func (o *GetEventLoopOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get event loop o k response has a 3xx status code
func (o *GetEventLoopOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get event loop o k response has a 4xx status code
func (o *GetEventLoopOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get event loop o k response has a 5xx status code
func (o *GetEventLoopOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get event loop o k response a status code equal to that given
func (o *GetEventLoopOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get event loop o k response
func (o *GetEventLoopOK) Code() int {
	return 200
}

func (o *GetEventLoopOK) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopOK  %+v", 200, o.Payload)
}

func (o *GetEventLoopOK) String() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopOK  %+v", 200, o.Payload)
}

func (o *GetEventLoopOK) GetPayload() *vproxy_client_model.EventLoop {
	return o.Payload
}

func (o *GetEventLoopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.EventLoop)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEventLoopBadRequest creates a GetEventLoopBadRequest with default headers values
func NewGetEventLoopBadRequest() *GetEventLoopBadRequest {
	return &GetEventLoopBadRequest{}
}

/*
GetEventLoopBadRequest describes a response with status code 400, with default header values.

invalid input parameters
*/
type GetEventLoopBadRequest struct {
	Payload *vproxy_client_model.Error400
}

// IsSuccess returns true when this get event loop bad request response has a 2xx status code
func (o *GetEventLoopBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get event loop bad request response has a 3xx status code
func (o *GetEventLoopBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get event loop bad request response has a 4xx status code
func (o *GetEventLoopBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get event loop bad request response has a 5xx status code
func (o *GetEventLoopBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get event loop bad request response a status code equal to that given
func (o *GetEventLoopBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get event loop bad request response
func (o *GetEventLoopBadRequest) Code() int {
	return 400
}

func (o *GetEventLoopBadRequest) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopBadRequest  %+v", 400, o.Payload)
}

func (o *GetEventLoopBadRequest) String() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopBadRequest  %+v", 400, o.Payload)
}

func (o *GetEventLoopBadRequest) GetPayload() *vproxy_client_model.Error400 {
	return o.Payload
}

func (o *GetEventLoopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEventLoopNotFound creates a GetEventLoopNotFound with default headers values
func NewGetEventLoopNotFound() *GetEventLoopNotFound {
	return &GetEventLoopNotFound{}
}

/*
GetEventLoopNotFound describes a response with status code 404, with default header values.

resource not found
*/
type GetEventLoopNotFound struct {
	Payload *vproxy_client_model.Error404
}

// IsSuccess returns true when this get event loop not found response has a 2xx status code
func (o *GetEventLoopNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get event loop not found response has a 3xx status code
func (o *GetEventLoopNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get event loop not found response has a 4xx status code
func (o *GetEventLoopNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get event loop not found response has a 5xx status code
func (o *GetEventLoopNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get event loop not found response a status code equal to that given
func (o *GetEventLoopNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get event loop not found response
func (o *GetEventLoopNotFound) Code() int {
	return 404
}

func (o *GetEventLoopNotFound) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopNotFound  %+v", 404, o.Payload)
}

func (o *GetEventLoopNotFound) String() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopNotFound  %+v", 404, o.Payload)
}

func (o *GetEventLoopNotFound) GetPayload() *vproxy_client_model.Error404 {
	return o.Payload
}

func (o *GetEventLoopNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error404)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEventLoopConflict creates a GetEventLoopConflict with default headers values
func NewGetEventLoopConflict() *GetEventLoopConflict {
	return &GetEventLoopConflict{}
}

/*
GetEventLoopConflict describes a response with status code 409, with default header values.

conflict
*/
type GetEventLoopConflict struct {
	Payload *vproxy_client_model.Error409
}

// IsSuccess returns true when this get event loop conflict response has a 2xx status code
func (o *GetEventLoopConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get event loop conflict response has a 3xx status code
func (o *GetEventLoopConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get event loop conflict response has a 4xx status code
func (o *GetEventLoopConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get event loop conflict response has a 5xx status code
func (o *GetEventLoopConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get event loop conflict response a status code equal to that given
func (o *GetEventLoopConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get event loop conflict response
func (o *GetEventLoopConflict) Code() int {
	return 409
}

func (o *GetEventLoopConflict) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopConflict  %+v", 409, o.Payload)
}

func (o *GetEventLoopConflict) String() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopConflict  %+v", 409, o.Payload)
}

func (o *GetEventLoopConflict) GetPayload() *vproxy_client_model.Error409 {
	return o.Payload
}

func (o *GetEventLoopConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error409)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEventLoopInternalServerError creates a GetEventLoopInternalServerError with default headers values
func NewGetEventLoopInternalServerError() *GetEventLoopInternalServerError {
	return &GetEventLoopInternalServerError{}
}

/*
GetEventLoopInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type GetEventLoopInternalServerError struct {
	Payload *vproxy_client_model.Error500
}

// IsSuccess returns true when this get event loop internal server error response has a 2xx status code
func (o *GetEventLoopInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get event loop internal server error response has a 3xx status code
func (o *GetEventLoopInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get event loop internal server error response has a 4xx status code
func (o *GetEventLoopInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get event loop internal server error response has a 5xx status code
func (o *GetEventLoopInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get event loop internal server error response a status code equal to that given
func (o *GetEventLoopInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get event loop internal server error response
func (o *GetEventLoopInternalServerError) Code() int {
	return 500
}

func (o *GetEventLoopInternalServerError) Error() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopInternalServerError  %+v", 500, o.Payload)
}

func (o *GetEventLoopInternalServerError) String() string {
	return fmt.Sprintf("[GET /event-loop-group/{elg}/event-loop/{el}][%d] getEventLoopInternalServerError  %+v", 500, o.Payload)
}

func (o *GetEventLoopInternalServerError) GetPayload() *vproxy_client_model.Error500 {
	return o.Payload
}

func (o *GetEventLoopInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(vproxy_client_model.Error500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
