name: standalone
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
      type:
        description: 'Type: compile/runtime'
        required: true
      arch:
        description: 'Arch: amd64/aarch64'
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      image_tag: vproxyio/${{ github.event.inputs.type }}:${{ github.event.inputs.version }}-${{ github.event.inputs.arch }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event.inputs.arch != 'amd64' }}
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - if: ${{ github.event.inputs.arch == 'amd64' }}
        name: build-amd64
        run: |
          docker build \
            --tag $image_tag \
            --push \
            ./misc/dockerfiles/vproxy-${{ github.event.inputs.type }}/
      - if: ${{ github.event.inputs.arch == 'aarch64' }}
        name: build-aarch64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag $image_tag \
            --provenance=false \
            --push \
            ./misc/dockerfiles/vproxy-${{ github.event.inputs.type }}-arm/
