name: unified
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
      type:
        description: 'Type: base/test'
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      image_tag: vproxyio/${{ github.event.inputs.type }}:${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $image_tag \
            --push \
            ./misc/dockerfiles/vproxy-${{ github.event.inputs.type }}/
